export const categories = [
  { value: "electronics", label: "Electronics" },
  { value: "computers", label: "Computers" },
  { value: "fashion", label: "Fashion" },
  { value: "home-kitchen", label: "Home & Kitchen" },
  { value: "sports-fitness", label: "Sports & Fitness" },
  { value: "clothing-apparel", label: "Clothing & Apparel" },
  { value: "beauty-personal-care", label: "Beauty & Personal Care" },
  { value: "toys-games", label: "Toys & Games" },
  { value: "books-stationery", label: "Books & Stationery" },
  { value: "automotive", label: "Automotive" },
  { value: "health-wellness", label: "Health & Wellness" },
  { value: "grocery-gourmet", label: "Grocery & Gourmet" },
  { value: "jewelry-accessories", label: "Jewelry & Accessories" },
  { value: "baby-kids", label: "Baby & Kids" },
  { value: "furniture-decor", label: "Furniture & Decor" },
  { value: "pet-supplies", label: "Pet Supplies" },
  { value: "office-supplies", label: "Office Supplies" },
  { value: "music-instruments", label: "Music & Instruments" },
  { value: "gaming", label: "Gaming" },
  { value: "outdoor-travel", label: "Outdoor & Travel" },
  { value: "art-crafts", label: "Art & Crafts" },
  { value: "footwear", label: "Footwear" },
  { value: "watches-eyewear", label: "Watches & Eyewear" },
  { value: "mobile-accessories", label: "Mobile Accessories" },
  { value: "laptops-computers", label: "Laptops & Computers" },
  { value: "cameras-photography", label: "Cameras & Photography" },
  { value: "kitchen-appliances", label: "Kitchen Appliances" },
  { value: "smart-home", label: "Smart Home" },
  { value: "gardening", label: "Gardening" },
  { value: "industrial-tools", label: "Industrial & Tools" },
  { value: "movies-entertainment", label: "Movies & Entertainment" },
  { value: "collectibles", label: "Collectibles" },
  { value: "luxury", label: "Luxury" },
  { value: "seasonal-festive", label: "Seasonal & Festive" },
  { value: "diy-hardware", label: "DIY & Hardware" },
  { value: "safety-security", label: "Safety & Security" },
  { value: "travel-luggage", label: "Travel & Luggage" },
];
